# Generated by Django 6.0.7 on 2026-07-11 18:22

import django.db.models.deletion
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('observation', 'Observation Record'), ('code', 'Source Code'), ('notebook', 'Notebook'), ('output', 'Output Screenshot'), ('reference', 'Reference Document'), ('other', 'Other')], default='observation', max_length=30)),
                ('file', models.FileField(upload_to='experiment_documents/%Y/%m/%d/', validators=[documents.models.validate_document_extension])),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('extracted_text', models.TextField(blank=True)),
                ('extraction_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=30)),
                ('extraction_error', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='experiments.experiment')),
            ],
        ),
    ]
