# Generated by Django 6.0.7 on 2026-07-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentdocument',
            name='structure_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='experimentdocument',
            name='structure_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='experimentdocument',
            name='structured_content',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
